services:
  django-app:
    container_name: django-app
    hostname: django-app
    build: 
      context: .
      dockerfile: ./docker/DockerFile-dj
    ports:
      - "8000:8000"
    volumes:
      - ./api:/usr/src/app
