services:

  db:
    container_name: db
    hostname: db
    image: postgres:12
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${DB_PORT}:${DB_PORT}
    expose:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    networks:
      - db-network

  django-app:
    container_name: django-app
    hostname: django-app
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    env_file:
      - .env
    build: 
      context: .
      dockerfile: ./docker/DockerFile-dj
    ports:
      - ${API_PORT}:${API_PORT}
    expose:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ./api:/usr/src/app
    networks:
      - db-network
      - api-network
  web:
    container_name: web
    hostname: web
    build: 
      context: .
      dockerfile: ./docker/dockerfile-web
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    expose:
      - ${WEB_PORT}:${WEB_PORT}
    volumes:
      - ./web:/usr/src/app
    networks:
      - api-network
  
networks:
  db-network :
    driver: bridge
  api-network:
    driver: bridge