FROM python:3.10-alpine

ENV PYTHONUNBUFFERED 1

WORKDIR /usr/src/app

COPY ../api/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY ../api .

RUN chmod +x ./app/django.sh

EXPOSE 8000

ENTRYPOINT [ "./app/django.sh" ]