/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as DashboardLayoutImport } from './routes/dashboard/_layout'
import { Route as DashboardLayoutIndexImport } from './routes/dashboard/_layout/index'
import { Route as LayoutSignupIndexImport } from './routes/_layout/signup/index'
import { Route as LayoutLoginIndexImport } from './routes/_layout/login/index'
import { Route as DashboardLayoutReservationIndexImport } from './routes/dashboard/_layout/reservation/index'
import { Route as DashboardLayoutProfileIndexImport } from './routes/dashboard/_layout/profile/index'
import { Route as DashboardLayoutHistoryIndexImport } from './routes/dashboard/_layout/history/index'
import { Route as DashboardLayoutProfileIdIndexImport } from './routes/dashboard/_layout/profile/$id/index'

// Create Virtual Routes

const DashboardImport = createFileRoute('/dashboard')()

// Create/Update Routes

const DashboardRoute = DashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const DashboardLayoutRoute = DashboardLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardLayoutIndexRoute = DashboardLayoutIndexImport.update({
  path: '/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)

const LayoutSignupIndexRoute = LayoutSignupIndexImport.update({
  path: '/signup/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutLoginIndexRoute = LayoutLoginIndexImport.update({
  path: '/login/',
  getParentRoute: () => LayoutRoute,
} as any)

const DashboardLayoutReservationIndexRoute =
  DashboardLayoutReservationIndexImport.update({
    path: '/reservation/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutProfileIndexRoute =
  DashboardLayoutProfileIndexImport.update({
    path: '/profile/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutHistoryIndexRoute =
  DashboardLayoutHistoryIndexImport.update({
    path: '/history/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutProfileIdIndexRoute =
  DashboardLayoutProfileIdIndexImport.update({
    path: '/profile/$id/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/_layout': {
      id: '/dashboard/_layout'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLayoutImport
      parentRoute: typeof DashboardRoute
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/login/': {
      id: '/_layout/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LayoutLoginIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/signup/': {
      id: '/_layout/signup/'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof LayoutSignupIndexImport
      parentRoute: typeof LayoutImport
    }
    '/dashboard/_layout/': {
      id: '/dashboard/_layout/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardLayoutIndexImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/dashboard/_layout/history/': {
      id: '/dashboard/_layout/history/'
      path: '/history'
      fullPath: '/dashboard/history'
      preLoaderRoute: typeof DashboardLayoutHistoryIndexImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/dashboard/_layout/profile/': {
      id: '/dashboard/_layout/profile/'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardLayoutProfileIndexImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/dashboard/_layout/reservation/': {
      id: '/dashboard/_layout/reservation/'
      path: '/reservation'
      fullPath: '/dashboard/reservation'
      preLoaderRoute: typeof DashboardLayoutReservationIndexImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/dashboard/_layout/profile/$id/': {
      id: '/dashboard/_layout/profile/$id/'
      path: '/profile/$id'
      fullPath: '/dashboard/profile/$id'
      preLoaderRoute: typeof DashboardLayoutProfileIdIndexImport
      parentRoute: typeof DashboardLayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  LayoutRoute: LayoutRoute.addChildren({
    LayoutIndexRoute,
    LayoutLoginIndexRoute,
    LayoutSignupIndexRoute,
  }),
  DashboardRoute: DashboardRoute.addChildren({
    DashboardLayoutRoute: DashboardLayoutRoute.addChildren({
      DashboardLayoutIndexRoute,
      DashboardLayoutHistoryIndexRoute,
      DashboardLayoutProfileIndexRoute,
      DashboardLayoutReservationIndexRoute,
      DashboardLayoutProfileIdIndexRoute,
    }),
  }),
})

/* prettier-ignore-end */
