/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LayoutSignupIndexImport } from './routes/_layout/signup/index'
import { Route as LayoutLoginIndexImport } from './routes/_layout/login/index'
import { Route as LayoutDashboardLayoutImport } from './routes/_layout/dashboard/_layout'
import { Route as LayoutDashboardLayoutIndexImport } from './routes/_layout/dashboard/_layout/index'
import { Route as LayoutDashboardLayoutReservationIndexImport } from './routes/_layout/dashboard/_layout/reservation/index'
import { Route as LayoutDashboardLayoutProfileIndexImport } from './routes/_layout/dashboard/_layout/profile/index'
import { Route as LayoutDashboardLayoutHistoryIndexImport } from './routes/_layout/dashboard/_layout/history/index'
import { Route as LayoutDashboardLayoutProfileIdIndexImport } from './routes/_layout/dashboard/_layout/profile/$id/index'

// Create Virtual Routes

const LayoutDashboardImport = createFileRoute('/_layout/dashboard')()

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutDashboardRoute = LayoutDashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSignupIndexRoute = LayoutSignupIndexImport.update({
  path: '/signup/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutLoginIndexRoute = LayoutLoginIndexImport.update({
  path: '/login/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutDashboardLayoutRoute = LayoutDashboardLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => LayoutDashboardRoute,
} as any)

const LayoutDashboardLayoutIndexRoute = LayoutDashboardLayoutIndexImport.update(
  {
    path: '/',
    getParentRoute: () => LayoutDashboardLayoutRoute,
  } as any,
)

const LayoutDashboardLayoutReservationIndexRoute =
  LayoutDashboardLayoutReservationIndexImport.update({
    path: '/reservation/',
    getParentRoute: () => LayoutDashboardLayoutRoute,
  } as any)

const LayoutDashboardLayoutProfileIndexRoute =
  LayoutDashboardLayoutProfileIndexImport.update({
    path: '/profile/',
    getParentRoute: () => LayoutDashboardLayoutRoute,
  } as any)

const LayoutDashboardLayoutHistoryIndexRoute =
  LayoutDashboardLayoutHistoryIndexImport.update({
    path: '/history/',
    getParentRoute: () => LayoutDashboardLayoutRoute,
  } as any)

const LayoutDashboardLayoutProfileIdIndexRoute =
  LayoutDashboardLayoutProfileIdIndexImport.update({
    path: '/profile/$id/',
    getParentRoute: () => LayoutDashboardLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/dashboard': {
      id: '/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/dashboard/_layout': {
      id: '/_layout/dashboard/_layout'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardLayoutImport
      parentRoute: typeof LayoutDashboardRoute
    }
    '/_layout/login/': {
      id: '/_layout/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LayoutLoginIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/signup/': {
      id: '/_layout/signup/'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof LayoutSignupIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/dashboard/_layout/': {
      id: '/_layout/dashboard/_layout/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof LayoutDashboardLayoutIndexImport
      parentRoute: typeof LayoutDashboardLayoutImport
    }
    '/_layout/dashboard/_layout/history/': {
      id: '/_layout/dashboard/_layout/history/'
      path: '/history'
      fullPath: '/dashboard/history'
      preLoaderRoute: typeof LayoutDashboardLayoutHistoryIndexImport
      parentRoute: typeof LayoutDashboardLayoutImport
    }
    '/_layout/dashboard/_layout/profile/': {
      id: '/_layout/dashboard/_layout/profile/'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof LayoutDashboardLayoutProfileIndexImport
      parentRoute: typeof LayoutDashboardLayoutImport
    }
    '/_layout/dashboard/_layout/reservation/': {
      id: '/_layout/dashboard/_layout/reservation/'
      path: '/reservation'
      fullPath: '/dashboard/reservation'
      preLoaderRoute: typeof LayoutDashboardLayoutReservationIndexImport
      parentRoute: typeof LayoutDashboardLayoutImport
    }
    '/_layout/dashboard/_layout/profile/$id/': {
      id: '/_layout/dashboard/_layout/profile/$id/'
      path: '/profile/$id'
      fullPath: '/dashboard/profile/$id'
      preLoaderRoute: typeof LayoutDashboardLayoutProfileIdIndexImport
      parentRoute: typeof LayoutDashboardLayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  LayoutRoute: LayoutRoute.addChildren({
    LayoutIndexRoute,
    LayoutDashboardRoute: LayoutDashboardRoute.addChildren({
      LayoutDashboardLayoutRoute: LayoutDashboardLayoutRoute.addChildren({
        LayoutDashboardLayoutIndexRoute,
        LayoutDashboardLayoutHistoryIndexRoute,
        LayoutDashboardLayoutProfileIndexRoute,
        LayoutDashboardLayoutReservationIndexRoute,
        LayoutDashboardLayoutProfileIdIndexRoute,
      }),
    }),
    LayoutLoginIndexRoute,
    LayoutSignupIndexRoute,
  }),
})

/* prettier-ignore-end */
